/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package peralcaldia;

import javax.swing.JOptionPane;
import util.cobrosiniciales;

/**
 *
 * @author alex
 */
public class gencobrosinmmesactual extends javax.swing.JInternalFrame {

    /**
     * Creates new form gencobrosinmmesactual
     */
    public gencobrosinmmesactual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncobrosninm = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        btncobrosninm.setText("Generar Cobros Inmuebles y Negocios Ingresados en el Periodo Actual");
        btncobrosninm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrosninmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncobrosninm)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(btncobrosninm)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncobrosninmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrosninmActionPerformed
        // TODO add your handling code here:
        int contador = 0;
        String salida = "";
        cobrosiniciales cobros = new cobrosiniciales();
        try {
            if (cobros.gencbnuevosinmuebles()) {
                contador = contador + 1;
            } else {
                salida = "No se encontraron nuevos inmuebles. ";
            }

            if (cobros.gencbnuevosnegocios()) {
                contador = contador + 1;
            } else if (contador == 1) {
                salida = "No se encontraron nuevos negocios";
            } else {
                salida = salida + ("Tampoco nuevos negocios");
            }

            if (contador == 2) {
                JOptionPane.showMessageDialog(this, "PROCESO TERMINADO ");
            } else {
                JOptionPane.showMessageDialog(this, "PROCESO TERMINADO. " + salida);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Hubo un error en el proceso contacte al administrador de su red");
        }

    }//GEN-LAST:event_btncobrosninmActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncobrosninm;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
