package peralcaldia.model;
// Generated 08-10-2013 10:26:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentarios generated by hbm2java
 */
@Entity
@Table(name="comentarios"
    ,schema="public"
)
public class Comentarios  implements java.io.Serializable {


     private int id;
     private Usuarios usuarios;
     private Publicaciones publicaciones;
     private String comentario;
     private Date fechacreacion;

    public Comentarios() {
    }

	
    public Comentarios(int id) {
        this.id = id;
    }
    public Comentarios(int id, Usuarios usuarios, Publicaciones publicaciones, String comentario, Date fechacreacion) {
       this.id = id;
       this.usuarios = usuarios;
       this.publicaciones = publicaciones;
       this.comentario = comentario;
       this.fechacreacion = fechacreacion;
    }
   
    @Id 
    @SequenceGenerator(name="secuencia_comentarios", sequenceName="Comentarios_Id_seq", allocationSize=1)    
    @Column(name="id", columnDefinition="serial", unique=true, nullable=false, precision=22, scale=0)
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="secuencia_comentarios")        
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuarios_id")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="publicaciones_id")
    public Publicaciones getPublicaciones() {
        return this.publicaciones;
    }
    
    public void setPublicaciones(Publicaciones publicaciones) {
        this.publicaciones = publicaciones;
    }
    
    @Column(name="comentario")
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechacreacion", length=13)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }




}


