package peralcaldia.model;
// Generated 08-10-2013 10:26:32 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name="estados"
    ,schema="public"
)
public class Estados  implements java.io.Serializable {


     private int id;
     private String estado;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
     private Set<Montosimpuestos> montosimpuestoses = new HashSet<Montosimpuestos>(0);
     private Set<Inmuebles> estadoses = new HashSet<Inmuebles>(0);

    public Estados() {
    }

	
    public Estados(int id) {
        this.id = id;
    }
    public Estados(int id, String estado, Set usuarioses, Set montosimpuestoses, Set estadoses) {
       this.id = id;
       this.estado = estado;
       this.usuarioses = usuarioses;
       this.montosimpuestoses = montosimpuestoses;
       this.estadoses = estadoses;
    }
   
    @Id 
    @SequenceGenerator(name="secuencia_estados",sequenceName="Estados_Id_seq", allocationSize=1)
    @Column(name="id", columnDefinition="serial", unique=true, nullable=false, precision=22, scale=0)
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="secuencia_estados")        
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="estado")
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Montosimpuestos> getMontosimpuestoses() {
        return this.montosimpuestoses;
    }
    
    public void setMontosimpuestoses(Set<Montosimpuestos> montosimpuestoses) {
        this.montosimpuestoses = montosimpuestoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estadosinm")
    public Set<Inmuebles> getEstadoses() {
        return estadoses;
    }

    public void setEstadoses(Set<Inmuebles> estadoses) {
        this.estadoses = estadoses;
    }

}


