package peralcaldia.model;
// Generated 08-10-2013 10:26:32 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
/*Clase Estados que representa a la entidad estado de la Base de Datos modelo de trabajo de  
 * hibernate con anotaciones*/
@Entity
@Table(name="estados"
    ,schema="public"
)
public class Estados  implements java.io.Serializable {


     private int id;
     private String estado;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
     private Set<Montosimpuestos> montosimpuestoses = new HashSet<Montosimpuestos>(0);
     private Set<Inmuebles> estadoses = new HashSet<Inmuebles>(0);
     private Set<Pagos> pagoes = new HashSet<Pagos>(0);
     private Set<Negocios> negocioses = new HashSet<Negocios>(0);
     private Set<Montosimpuestosnegocios> mntimpuestoes = new HashSet<Montosimpuestosnegocios>(0);
     private Set<Boleta> boletaes =  new HashSet<Boleta>(0);
     private Set<Formulas> formulaes = new HashSet<Formulas>(0);
     private Set<Tiposcomercio> tiposcomercioes = new HashSet<Tiposcomercio>(0);
     private Set<Giros> giroes = new HashSet<Giros>(0);
     private Set<Pagosadelantados> pagosadelantadoses = new HashSet<Pagosadelantados>(0);

    public Estados() {
    }

	
    public Estados(int id) {
        this.id = id;
    }
    public Estados(int id, String estado, Set usuarioses, Set montosimpuestoses, Set estadoses, Set pagoes, Set negocioses, Set mntimpuestoes, Set boletaes, Set formulaes, Set tiposcomercioes, Set giroes, Set pagosadelantadoses) {
       this.id = id;
       this.estado = estado;
       this.usuarioses = usuarioses;
       this.montosimpuestoses = montosimpuestoses;
       this.estadoses = estadoses;
       this.pagoes = pagoes;
       this.negocioses = negocioses;
       this.mntimpuestoes = mntimpuestoes;
       this.boletaes =  boletaes;
       this.formulaes = formulaes;
       this.tiposcomercioes = tiposcomercioes;
       this.giroes = giroes;
       this.pagosadelantadoses = pagosadelantadoses;
    }
   
    @Id 
    @SequenceGenerator(name="secuencia_estados",sequenceName="Estados_Id_seq", allocationSize=1)
    @Column(name="id", columnDefinition="serial", unique=true, nullable=false, precision=22, scale=0)
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="secuencia_estados")        
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="estado")
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Montosimpuestos> getMontosimpuestoses() {
        return this.montosimpuestoses;
    }
    
    public void setMontosimpuestoses(Set<Montosimpuestos> montosimpuestoses) {
        this.montosimpuestoses = montosimpuestoses;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estadosinm")
    public Set<Inmuebles> getEstadoses() {
        return estadoses;
    }

    public void setEstadoses(Set<Inmuebles> estadoses) {
        this.estadoses = estadoses;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estadosid")
    public Set<Pagos> getPagoes() {
        return pagoes;
    }

    public void setPagoes(Set<Pagos> pagoes) {
        this.pagoes = pagoes;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Negocios> getNegocioses() {
        return negocioses;
    }

    public void setNegocioses(Set<Negocios> negocioses) {
        this.negocioses = negocioses;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Montosimpuestosnegocios> getMntimpuestoes() {
        return mntimpuestoes;
    }

    public void setMntimpuestoes(Set<Montosimpuestosnegocios> mntimpuestoes) {
        this.mntimpuestoes = mntimpuestoes;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")    
    public Set<Boleta> getBoletaes() {
        return boletaes;
    }

    public void setBoletaes(Set<Boleta> boletaes) {
        this.boletaes = boletaes;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Formulas> getFormulaes() {
        return formulaes;
    }

    public void setFormulaes(Set<Formulas> formulaes) {
        this.formulaes = formulaes;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Giros> getGiroes() {
        return giroes;
    }

    public void setGiroes(Set<Giros> giroes) {
        this.giroes = giroes;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")    
    public Set<Tiposcomercio> getTiposcomercioes() {
        return tiposcomercioes;
    }

    public void setTiposcomercioes(Set<Tiposcomercio> tiposcomercioes) {
        this.tiposcomercioes = tiposcomercioes;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")    
    public Set<Pagosadelantados> getPagosadelantadoses() {
        return pagosadelantadoses;
    }

    public void setPagosadelantadoses(Set<Pagosadelantados> pagosadelantadoses) {
        this.pagosadelantadoses = pagosadelantadoses;
    }

}


