package peralcaldia.model;
// Generated 08-10-2013 10:26:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inmuebles generated by hbm2java
 */
@Entity
@Table(name="inmuebles"
    ,schema="public"
)
public class Inmuebles  implements java.io.Serializable {


     private int id;
     private Zonas zonas;
     private Contribuyentes contribuyentes;
     private String direccion;
     private String telefono;
     private String tomo1;
     private String folio1;
     private String tomo2;
     private String folio2;
     private String tomoreal;
     private BigDecimal metros_lineales;
     private BigDecimal metros_cuadrados;
     private Date fecharegistro;
     private Estados estadosinm;
     private String cuentacorriente;
     private String sector;
     private String parcela;
     private String correlativoinmueble;
     private BigDecimal adoquinado;
     private Set<Impuestosinmuebles> impuestosinmuebleses = new HashSet<Impuestosinmuebles>(0);
     private Set<Pagos> pagoses = new HashSet<Pagos>(0);
     private Set<historico_inmueble> historicosinmuebles = new HashSet<historico_inmueble>(0);

    public Inmuebles() {
    }

	
    public Inmuebles(int id) {
        this.id = id;
    }
    public Inmuebles(int id, Zonas zonas, Contribuyentes contribuyentes, String direccion, String telefono, String tomo1, String folio1, String tomo2, String folio2, String tomoreal, BigDecimal metros_lineales, BigDecimal metros_cuadrados,Date fecharegistro, Estados estadosinm, Set impuestosinmuebleses, Set pagoses, Set historicosinmuebles, String cuentacorriente, String sector, String parcela, String correlativoinmueble, BigDecimal adoquinado) {
       this.id = id;
       this.zonas = zonas;
       this.contribuyentes = contribuyentes;
       this.direccion = direccion;
       this.telefono = telefono;
       this.tomo1 = tomo1;
       this.folio1 = folio1;
       this.tomo2 = tomo2;
       this.folio2 = folio2;
       this.tomoreal = tomoreal;
       this.impuestosinmuebleses = impuestosinmuebleses;
       this.pagoses = pagoses;
       this.metros_lineales = metros_lineales;
       this.metros_cuadrados = metros_cuadrados;
       this.fecharegistro= fecharegistro;
       this.estadosinm = estadosinm;
       this.historicosinmuebles = historicosinmuebles;
       this.cuentacorriente =  cuentacorriente;
       this.sector = sector;
       this.parcela = parcela;
       this.correlativoinmueble = correlativoinmueble;
       this.adoquinado = adoquinado;
    }
   
    @Id 
    @SequenceGenerator(name="secuencia_inmuebles",sequenceName="inmuebles_id_seq", allocationSize=1)
    @Column(name="id", columnDefinition="serial", unique=true, nullable=false, precision=22, scale=0)
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="secuencia_inmuebles")    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="zonas_id")
    public Zonas getZonas() {
        return this.zonas;
    }
    
    public void setZonas(Zonas zonas) {
        this.zonas = zonas;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contribuyentes_id")
    public Contribuyentes getContribuyentes() {
        return this.contribuyentes;
    }
    
    public void setContribuyentes(Contribuyentes contribuyentes) {
        this.contribuyentes = contribuyentes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estados_id")
    public Estados getEstadosinm() {
        return estadosinm;
    }

    public void setEstadosinm(Estados estadosinm) {
        this.estadosinm = estadosinm;
    }
    
    @Column(name="direccion")
    public String getDireccion() {
        return this.direccion;
    }


    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="telefono")
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="tomo1")
    public String getTomo1() {
        return this.tomo1;
    }
    
    public void setTomo1(String tomo1) {
        this.tomo1 = tomo1;
    }
    
    @Column(name="folio1")
    public String getFolio1() {
        return this.folio1;
    }
    
    public void setFolio1(String folio1) {
        this.folio1 = folio1;
    }
    
    @Column(name="tomo2")
    public String getTomo2() {
        return this.tomo2;
    }
    
    public void setTomo2(String tomo2) {
        this.tomo2 = tomo2;
    }
    
    @Column(name="folio2")
    public String getFolio2() {
        return this.folio2;
    }
    
    public void setFolio2(String folio2) {
        this.folio2 = folio2;
    }
    
    @Column(name="tomoreal")
    public String getTomoreal() {
        return this.tomoreal;
    }
    
    public void setTomoreal(String tomoreal) {
        this.tomoreal = tomoreal;
    }

    @Column(name="metros_lineales")    
    public BigDecimal getMetros_lineales() {
        return metros_lineales;
    }

    public void setMetros_lineales(BigDecimal metros_lineales) {
        this.metros_lineales = metros_lineales;
    }

    @Column(name="metros_cuadrados")    
    public BigDecimal getMetros_cuadrados() {
        return metros_cuadrados;
    }

    public void setMetros_cuadrados(BigDecimal metros_cuadrados) {
        this.metros_cuadrados = metros_cuadrados;
    }        
    
    @Temporal(TemporalType.DATE)
    @Column(name="fecharegistro", length=13)    
    public Date getFecharegistro() {
        return fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }    
        
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="inmuebles")
    public Set<Impuestosinmuebles> getImpuestosinmuebleses() {
        return this.impuestosinmuebleses;
    }
    
    public void setImpuestosinmuebleses(Set<Impuestosinmuebles> impuestosinmuebleses) {
        this.impuestosinmuebleses = impuestosinmuebleses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="inmuebles")
    public Set<Pagos> getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set<Pagos> pagoses) {
        this.pagoses = pagoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="inmuebleshid")

    public Set<historico_inmueble> getHistoricosinmuebles() {
        return historicosinmuebles;
    }

    public void setHistoricosinmuebles(Set<historico_inmueble> historicosinmuebles) {
        this.historicosinmuebles = historicosinmuebles;
    }
    
    @Column(name="cuentacorriente")
    public String getCuentacorriente() {
        return cuentacorriente;
    }

    public void setCuentacorriente(String cuentacorriente) {
        this.cuentacorriente = cuentacorriente;
    }
    
    @Column(name="sector")
    public String getSector() {
        return sector;
    }

    public void setSector(String sector) {
        this.sector = sector;
    }
    
    @Column(name="parcela")
    public String getParcela() {
        return parcela;
    }

    public void setParcela(String parcela) {
        this.parcela = parcela;
    }
    
    @Column(name="correlativoinmueble")
    public String getCorrelativoinmueble() {
        return correlativoinmueble;
    }

    public void setCorrelativoinmueble(String correlativoinmueble) {
        this.correlativoinmueble = correlativoinmueble;
    }
    
    @Column(name="adoquinado")
    public BigDecimal getAdoquinado() {
        return adoquinado;
    }

    public void setAdoquinado(BigDecimal adoquinado) {
        this.adoquinado = adoquinado;
    }
    
}


