package peralcaldia.model;
// Generated 08-10-2013 10:26:32 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
/*Clase Pagos que representa a la entidad pagos de la Base de Datos modelo de trabajo de  
 * hibernate con anotaciones*/
@Entity
@Table(name="pagos"
    ,schema="public"
)
public class Pagos  implements java.io.Serializable {


     private int id;
     private Inmuebles inmuebles;
     private Date fechapago;
     private BigDecimal monto;
     private String norecibo;
     private String mespagado;
     private int descuento;
     private BigDecimal montopagado;
     private String comentario;
     private Estados estadosid;
     private Negocios negocios;
     private Boleta boletas;
     private Set<Detallepagos> detallepagoes = new HashSet<Detallepagos>(0);

    public Pagos() {
    }

	
    public Pagos(int id) {
        this.id = id;
    }
    public Pagos(int id, Inmuebles inmuebles, Date fechapago, BigDecimal monto, String norecibo, String mespagado, int descuento, BigDecimal montopagado, String comentario, Estados estadosid, Negocios negocios, Boleta boletas, Set detallepagoes) {
       this.id = id;
       this.inmuebles = inmuebles;
       this.fechapago = fechapago;
       this.monto = monto;
       this.norecibo = norecibo;
       this.mespagado = mespagado;
       this.descuento = descuento;
       this.montopagado = montopagado;
       this.comentario = comentario;
       this.estadosid = estadosid;
       this.negocios = negocios;
       this.boletas = boletas;
       this.detallepagoes = detallepagoes;
    }
   
    @Id 
    @SequenceGenerator(name="secuencia_pagos",sequenceName="pagos_id_seq", allocationSize=1)
    @Column(name="id", columnDefinition="serial", unique=true, nullable=false, precision=22, scale=0)
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="secuencia_pagos")    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inmuebles_id")
    public Inmuebles getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Inmuebles inmuebles) {
        this.inmuebles = inmuebles;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechapago", length=13)
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }
    
    @Column(name="monto", precision=17, scale=17)
    public BigDecimal getMonto() {
        return this.monto.setScale(2,RoundingMode.HALF_EVEN);
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    
    @Column(name="norecibo")
    public String getNorecibo() {
        return this.norecibo;
    }
    
    public void setNorecibo(String norecibo) {
        this.norecibo = norecibo;
    }
    
    @Column(name="mespagado")
    public String getMespagado() {
        return this.mespagado;
    }
    
    public void setMespagado(String mespagado) {
        this.mespagado = mespagado;
    }
    
    @Column(name="descuento")    
    public int getDescuento() {
        return descuento;
    }

    public void setDescuento(int descuento) {
        this.descuento = descuento;
    }

    @Column(name="montopagado")    
    public BigDecimal getMontopagado() {
        return montopagado;
    }

    public void setMontopagado(BigDecimal montopagado) {
        this.montopagado = montopagado;
    }
    
    @Column(name="comentario")
    public String getComentario() {
        return comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    
@ManyToOne(fetch=FetchType.LAZY)    
    @JoinColumn(name="estados_id")
    public Estados getEstadosid() {
        return estadosid;
    }

    public void setEstadosid(Estados estadosid) {
        this.estadosid = estadosid;
    }
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="negocios_id")
    public Negocios getNegocios() {
        return negocios;
    }

    public void setNegocios(Negocios negocios) {
        this.negocios = negocios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="boleta_id")
    public Boleta getBoletas() {
        return boletas;
    }

    public void setBoletas(Boleta boletas) {
        this.boletas = boletas;
    }
    
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pagos")
    public Set<Detallepagos> getDetallepagoes() {
        return detallepagoes;
    }

    public void setDetallepagoes(Set<Detallepagos> detallepagoes) {
        this.detallepagoes = detallepagoes;
    }    
}


