package peralcaldia.model;
// Generated 08-10-2013 10:26:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name="pagos"
    ,schema="public"
)
public class Pagos  implements java.io.Serializable {


     private int id;
     private Inmuebles inmuebles;
     private Date fechapago;
     private Double monto;
     private String norecibo;
     private String mespagado;

    public Pagos() {
    }

	
    public Pagos(int id) {
        this.id = id;
    }
    public Pagos(int id, Inmuebles inmuebles, Date fechapago, Double monto, String norecibo, String mespagado) {
       this.id = id;
       this.inmuebles = inmuebles;
       this.fechapago = fechapago;
       this.monto = monto;
       this.norecibo = norecibo;
       this.mespagado = mespagado;
    }
   
    @Id 
    @SequenceGenerator(name="secuencia_pagos",sequenceName="pagos_id_seq", allocationSize=1)
    @Column(name="id", columnDefinition="serial", unique=true, nullable=false, precision=22, scale=0)
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="secuencia_pagos")    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inmuebles_id")
    public Inmuebles getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Inmuebles inmuebles) {
        this.inmuebles = inmuebles;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechapago", length=13)
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }
    
    @Column(name="monto", precision=17, scale=17)
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    
    @Column(name="norecibo")
    public String getNorecibo() {
        return this.norecibo;
    }
    
    public void setNorecibo(String norecibo) {
        this.norecibo = norecibo;
    }
    
    @Column(name="mespagado")
    public String getMespagado() {
        return this.mespagado;
    }
    
    public void setMespagado(String mespagado) {
        this.mespagado = mespagado;
    }




}


