package peralcaldia.model;
// Generated 08-10-2013 10:26:32 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
/*Clase Usuarios que representa a la entidad usuarios de la Base de Datos modelo de trabajo de  
 * hibernate con anotaciones*/
@Entity
@Table(name="usuarios"
    ,schema="public"
)
public class Usuarios  implements java.io.Serializable {


     private int id;
     private Roles roles;
     private Estados estados;
     private String nombres;
     private String apellidos;
     private String alias;
     private String password;
     private String email;
     private String telefonofijo;
     private String telefonocelular;
     private String direccion;
     private Set<Publicaciones> publicacioneses = new HashSet<Publicaciones>(0);
     private Set<Contribuyentes> contribuyenteses = new HashSet<Contribuyentes>(0);
     private Set<Comentarios> comentarioses = new HashSet<Comentarios>(0);

    public Usuarios() {
    }

	
    public Usuarios(int id) {
        this.id = id;
    }
    public Usuarios(int id, Roles roles, Estados estados, String nombres, String apellidos, String alias, String password, String email, String telefonofijo, String telefonocelular, String direccion, Set publicacioneses, Set contribuyenteses, Set comentarioses) {
       this.id = id;
       this.roles = roles;
       this.estados = estados;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.alias = alias;
       this.password = password;
       this.email = email;
       this.telefonofijo = telefonofijo;
       this.telefonocelular = telefonocelular;
       this.direccion = direccion;
       this.publicacioneses = publicacioneses;
       this.contribuyenteses = contribuyenteses;
       this.comentarioses = comentarioses;
    }
   
    @Id 
    @SequenceGenerator(name="secuencia_usuario",sequenceName="Usuarios_Id_seq", allocationSize=1)
    @Column(name="id", columnDefinition="serial", unique=true, nullable=false, precision=22, scale=0)
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator="secuencia_usuario")    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="roles_id")
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estados_id")
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    
    @Column(name="nombres")
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="apellidos")
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="alias")
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="telefonofijo")
    public String getTelefonofijo() {
        return this.telefonofijo;
    }
    
    public void setTelefonofijo(String telefonofijo) {
        this.telefonofijo = telefonofijo;
    }
    
    @Column(name="telefonocelular")
    public String getTelefonocelular() {
        return this.telefonocelular;
    }
    
    public void setTelefonocelular(String telefonocelular) {
        this.telefonocelular = telefonocelular;
    }
    
    @Column(name="direccion")
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Publicaciones> getPublicacioneses() {
        return this.publicacioneses;
    }
    
    public void setPublicacioneses(Set<Publicaciones> publicacioneses) {
        this.publicacioneses = publicacioneses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Contribuyentes> getContribuyenteses() {
        return this.contribuyenteses;
    }
    
    public void setContribuyenteses(Set<Contribuyentes> contribuyenteses) {
        this.contribuyenteses = contribuyenteses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<Comentarios> getComentarioses() {
        return this.comentarioses;
    }
    
    public void setComentarioses(Set<Comentarios> comentarioses) {
        this.comentarioses = comentarioses;
    }




}


