/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package peralcaldia.MantenimientosIngreso;

import controller.AbstractDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import util.codemd5;
import peralcaldia.model.Contribuyentes;
import peralcaldia.model.Usuarios;
import peralcaldia.model.Roles;
import peralcaldia.model.Estados;
import util.GCMPNativos;

/**
 *
 * @author alex
 */
/*Pantalla destinada para el ingreso de nuevos contribuyentes al sistema*/
public class addcontribuyente extends javax.swing.JInternalFrame {

    AbstractDAO dao = new AbstractDAO();
    GCMPNativos componentes = new GCMPNativos();
    DefaultComboBoxModel contrimodel = new DefaultComboBoxModel();
    DefaultComboBoxModel estmodel = new DefaultComboBoxModel();

    /**
     * Creates new form addcontribuyente
     */
    public addcontribuyente() {
        initComponents();
        cmbrol.setModel(contrimodel);
        cmbestado.setModel(estmodel);
        fillComboBoxrol();
        fillComboBoxestado();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*Metodo Utilizado para la carga de los roles que pueden ser asignados a los contribuyentes*/
    private void fillComboBoxrol() {
        List lista = null;        
        try {
            lista = dao.findByWhereStatement("Select rol from Roles where rol = 'CONTRIBUYENTE' ");
            componentes.llenarmodelo(contrimodel, lista);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /*Metodo Utilizado para la carga de los posibles estados de los contribuyentes.*/
    private void fillComboBoxestado() {
        List lista = null;        
        try {
            lista = dao.findByWhereStatement("Select estado from Estados where estado = 'ACTIVO' or estado='INACTIVO' ");
            componentes.llenarmodelo(estmodel, lista);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /*Metodo utilizado para la verificacion de los datos introducidos, inicializacion de la nueva instancia
     * y guardado de la misma en el sistema*/
    public void guardarcontribuyente() {
        //Declaracion de Variables.
        String key;
        Usuarios user = new Usuarios();
        Contribuyentes contribuyente = new Contribuyentes();
        Roles rl = new Roles();
        Estados st = new Estados();

        if (!txtnombres.getText().isEmpty() && !txtapellidos.getText().isEmpty() && !txtusername.getText().isEmpty() && !txtpassword.getText().isEmpty() && !txtdireccion.getText().isEmpty() && !txttelefono.getText().isEmpty() && !txtdui.getText().isEmpty() && !txtnit.getText().isEmpty() && !txtniss.getText().isEmpty() && !cmbestado.getSelectedItem().toString().equals("-") && !cmbrol.getSelectedItem().toString().equals("-")) {
            //Encriptando password.
            key = codemd5.getmd5(txtpassword.getText());
            //Seteando las variables a las valores introducidos por el usuario.
            //Usuario
            rl = (Roles) dao.findByWhereStatementoneobj(Roles.class, "rol='" + cmbrol.getSelectedItem().toString() + "'");
            st = (Estados) dao.findByWhereStatementoneobj(Estados.class, "estado='" + cmbestado.getSelectedItem().toString() + "'");
            user.setAlias(txtusername.getText());
            user.setApellidos(txtapellidos.getText().toUpperCase());
            user.setDireccion(txtdireccion.getText().toUpperCase());
            user.setEmail(txtemail.getText());
            user.setEstados(st);
            user.setNombres(txtnombres.getText().toUpperCase());
            user.setPassword(key);
            user.setRoles(rl);
            user.setTelefonocelular(txtmovil.getText());
            user.setTelefonofijo(txttelefono.getText());
            //Contribuyente       
            
            contribuyente.setNiss(txtniss.getText());

            contribuyente.setUsuarios(user);
            try {
                Usuarios cmpalias = new Usuarios();
                Contribuyentes cnt = new Contribuyentes();
                //Comprobando que el alias sea Unico.
                cmpalias = (Usuarios) dao.findByWhereStatementoneobj(Usuarios.class, "alias='" + txtusername.getText().toUpperCase() + "'");
                if (cmpalias == null) {
                    //Comprobando que el Email sea Unico.
                    cmpalias = (Usuarios) dao.findByWhereStatementoneobj(Usuarios.class, "email='" + txtemail.getText() + "'");
                    if (cmpalias == null) {
                        //Comprobando que el DUI no haya sido registrado.
                        cnt = (Contribuyentes) dao.findByWhereStatementmaximoobjeto(Contribuyentes.class, "dui ='" + txtdui.getText() + "'");
                        if (cnt == null) {
                            contribuyente.setDui(txtdui.getText());
                            //Comprobando que el Nit/Nit Juridico no se encuentre registrado para otro contribuyente.
                            cnt = (Contribuyentes) dao.findByWhereStatementmaximoobjeto(Contribuyentes.class, "nit ='" + txtnit.getText() + "' or nitjuridico='" + txtnit.getText() + "'");
                            if (cnt == null) {
                                if (jrnit.isSelected() == true) {
                                    contribuyente.setNit(txtnit.getText());
                                } else {
                                    contribuyente.setNitjuridico(txtnit.getText());
                                }
                                //Comprobando que el Niss sea unico.
                                cnt = (Contribuyentes) dao.findByWhereStatementmaximoobjeto(Contribuyentes.class, "niss ='" + txtniss.getText() + "'");
                                if (cnt == null) {
                                    contribuyente.setNiss(txtniss.getText());
                                    contribuyente.setUsuarios(user);
                                    dao.save(user);
                                    dao.save(contribuyente);
                                    JOptionPane.showMessageDialog(this, "Guardado Completado");
                                    limpiarpantalla();
                                }else{
                                    JOptionPane.showMessageDialog(this, "El Niss Ingresado ya se encuentra asignado. Verificar Datos");
                                }
                            }else{
                                JOptionPane.showMessageDialog(this, "El Nit/NJuridico ya se encuentra registrado para otro contribuyente. Verificar Datos");
                            }
                        }else{
                            JOptionPane.showMessageDialog(this, "El Número de DUI ya se encuentra Registrado. Verificar Datos.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Direccion de Email en Uso, Ingresar uno diferente");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario ya existe, por favor ingresar un usuario diferente");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Hubo un problema al guardar la información, por favor intente mas tarde");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor ingresar todos los campos marcados con '*' ");
        }
    }

    /*Metodo Para limpiar la pantalla despues de un guardado exitoso*/
    public void limpiarpantalla() {
        txtapellidos.setText("");
        txtdireccion.setText("");
        txtdui.setText("");
        txtemail.setText("");
        txtmovil.setText("");
        txtnit.setText("");
        txtnit.setText("");
        txtnombres.setText("");
        txtpassword.setText("");
        txttelefono.setText("");
        txtusername.setText("");
        txtniss.setText("");
        fillComboBoxrol();
        fillComboBoxestado();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jrnit = new javax.swing.JRadioButton();
        jrnjuridico = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cmbrol = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbestado = new javax.swing.JComboBox();
        btnguardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtemail = new componentesheredados.MailTextField();
        txtnombres = new componentesheredados.LettersJTextField();
        txtapellidos = new componentesheredados.LettersJTextField();
        txttelefono = new componentesheredados.PhoneJTextField();
        txtmovil = new componentesheredados.PhoneJTextField();
        txtdui = new componentesheredados.DUITextField();
        txtnit = new componentesheredados.NitJTextField();
        jLabel12 = new javax.swing.JLabel();
        txtniss = new componentesheredados.NumberJTextField();

        setClosable(true);
        setIconifiable(true);

        jLabel3.setText("* Nombres:");

        jLabel4.setText("* Apellidos:");

        jLabel5.setText("* Username:");

        jLabel6.setText("* Password:");

        jLabel7.setText("Email:");

        jLabel8.setText("* Telefono:");

        jLabel9.setText("Celular:");

        jLabel10.setText("* Dirección:");

        jLabel11.setText("* DUI:");

        jLabel13.setText("* NISS:");

        buttonGroup1.add(jrnit);
        jrnit.setSelected(true);
        jrnit.setText("NIT");

        buttonGroup1.add(jrnjuridico);
        jrnjuridico.setText("NIT JURIDICO");

        jLabel1.setText("* ROL:");

        cmbrol.setName(""); // NOI18N

        jLabel2.setText("* ESTADO:");

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jButton1.setLabel("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            txttelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtmovil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtdui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtnit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrnit)
                        .addGap(42, 42, 42)
                        .addComponent(jrnjuridico)
                        .addGap(18, 18, 18)
                        .addComponent(txtnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtusername))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(txtmovil, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(14, 14, 14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpassword)
                                .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtdireccion)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtdui, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtniss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtnombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbrol, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(txtdui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtniss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrnit)
                    .addComponent(jrnjuridico)
                    .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        guardarcontribuyente();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbestado;
    private javax.swing.JComboBox cmbrol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrnit;
    private javax.swing.JRadioButton jrnjuridico;
    private componentesheredados.LettersJTextField txtapellidos;
    private javax.swing.JTextField txtdireccion;
    private componentesheredados.DUITextField txtdui;
    private componentesheredados.MailTextField txtemail;
    private componentesheredados.PhoneJTextField txtmovil;
    private componentesheredados.NumberJTextField txtniss;
    private componentesheredados.NitJTextField txtnit;
    private componentesheredados.LettersJTextField txtnombres;
    private javax.swing.JPasswordField txtpassword;
    private componentesheredados.PhoneJTextField txttelefono;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
