/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package peralcaldia.MantenimientosIngreso;

import com.sun.org.apache.bcel.internal.generic.LCONST;
import controller.AbstractDAO;
import controller.GrDAO;
import controller.UserDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import peralcaldia.model.Usuarios;
import peralcaldia.model.Contribuyentes;
import peralcaldia.model.Negocios;
import peralcaldia.model.Estados;
import peralcaldia.model.Tiposcomercio;
import peralcaldia.model.Giros;
import peralcaldia.model.Montosimpuestosnegocios;
import util.GCMPNativos;
import util.codemd5;

/**
 *
 * @author alex
 */
/*Pantalla Utilizada para agregar nuevos negocios al sistema de acuero a un contribuyente en especifico*/
public class addnegocio extends javax.swing.JInternalFrame {

    UserDAO dao = new UserDAO();
    Contribuyentes contribuyente = new Contribuyentes();
    GCMPNativos componentes = new GCMPNativos();
    DefaultComboBoxModel modelocontribuyente = new DefaultComboBoxModel();
    DefaultComboBoxModel modelogiro = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloactividad = new DefaultComboBoxModel();
    AbstractDAO gDao = new AbstractDAO();
    Giros giro = new Giros();

    /**
     * Creates new form addnegocio
     */
    public addnegocio() {
        initComponents();
        modelocontribuyente.addElement("-");
        modelogiro.addElement("-");
        modeloactividad.addElement("-");
        cmbcontribuyente.setModel(modelocontribuyente);
        cmbactividad.setModel(modeloactividad);
        cmbgiro.setModel(modelogiro);
        txtnombres1.setEnabled(false);
        txtdui1.setEnabled(false);
        txtnit1.setEnabled(false);
        LlenarComboGiros();
        jdfecharegistro.setDate(new Date());
        jdappmonto.setDate(new Date());
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 4);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*Buscar Contribuyentes por Nombres*/
    public void BuscarContribuyenteNombres() {
        List lusuarios = null;
        try {
            /*Buscando Usuarios que coincidan con el nombre o porcion indicada en el Textbox*/
            if (!txtnombres1.getText().isEmpty()) {
                lusuarios = dao.find_usuarios_whereStatement(" a.nombres || ' ' || a.apellidos || ' - DUI:' || b.dui like '%" + txtnombres1.getText().toUpperCase() + "%' and a.roles = 3");
                if (lusuarios != null && lusuarios.size() > 0) {
                    componentes.llenarmodelo(modelocontribuyente, lusuarios);
                    contribuyente = null;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la busqueda de usuarios");
            System.out.println(e.toString());
        }
    }

    /*Buscar Contribuyentes por DUI*/
    public void BuscarContribuyentesDui() {
        List lusuarios = null;
        try {
            if (!txtdui1.getText().isEmpty() && !txtdui1.getText().equals("-")) {
                contribuyente = (Contribuyentes) dao.findByWhereStatementoneobj(Contribuyentes.class, "dui = '" + this.txtdui1.getText() + "'");
                if (contribuyente != null) {
                    lusuarios = new ArrayList();
                    lusuarios.add(contribuyente.getUsuarios().getNombres() + " " + contribuyente.getUsuarios().getApellidos());
                    componentes.llenarmodelo(modelocontribuyente, lusuarios);
                } else {
                    JOptionPane.showMessageDialog(this, "No Existen Contribuyentes registrados con el DUI ingresado");

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la busqueda de usuarios");
            System.out.println(e.toString());
        }

    }

    /*Buscar Contribuyentes por NIT*/
    public void BuscarContribuyenteNit() {
        List lusuarios = null;
        try {
            if (!txtnit1.getText().isEmpty() && !txtnit1.getText().equals("----")) {
                contribuyente = (Contribuyentes) dao.findByWhereStatementoneobj(Contribuyentes.class, "nit = '" + this.txtnit1.getText() + "'");
                if (contribuyente != null) {
                    lusuarios = new ArrayList();
                    lusuarios.add(contribuyente.getUsuarios().getNombres() + " " + contribuyente.getUsuarios().getApellidos());
                    componentes.llenarmodelo(modelocontribuyente, lusuarios);
                } else {
                    JOptionPane.showMessageDialog(this, "No Existen Contribuyentes registrados con el NIT ingresado");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la busqueda de usuarios");
            System.out.println(e.toString());
        }
    }

    /*Metodo utilizado para cargar los giros ingresados y activos en el sistema*/
    public void LlenarComboGiros() {
        List lista = null;
        GrDAO misGiros = new GrDAO();

        try {
            lista = misGiros.find_giros_whereStatement(" estados_id = 1");
            componentes.llenarmodelo(modelogiro, lista);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la Carga de Giros de las Empresas");
            System.out.println(e.toString());
        }
    }

    /*Metodo Utilizado para cargar los diferentes tipos de actividades comerciales de acuerdo a los giros
     * seleccionados*/
    public void LlenarComboActividad() {
        List listaActividad = null;
        try {
            giro = (Giros) dao.findByWhereStatementoneobj(Giros.class, "descripcion = '" + cmbgiro.getSelectedItem().toString() + "' and estados_id = 1");
            listaActividad = dao.findByWhereStatement("select actividadeconomica from Tiposcomercio where giros_id = ' " + giro.getId() + "' and estados_id=1");
            componentes.llenarmodelo(modeloactividad, listaActividad);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la carga de los tipos relacionados al giro");
            e.printStackTrace();
        }
    }

    /*Metodo utilizado para verificar, inicializar y configurar las instancias de los nuevos negocios una vez estas
     * cumplan con los requisitos*/
    public void GuardarDatosNegocio() {
        Tiposcomercio tipo = new Tiposcomercio();
        Estados activo = new Estados();
        Negocios negocio = new Negocios();
        Negocios tmpnego = new Negocios();
        Montosimpuestosnegocios montoimpuestonegocio = new Montosimpuestosnegocios();
        /*Definición y Seteo de los Datos a Ingresar*/
        try {
            if (!txtnempresa.getText().isEmpty() && !txtdireccion.getText().isEmpty() && !cmbgiro.getSelectedItem().toString().equals("-") && !cmbactividad.getSelectedItem().toString().equals("-")) {
                tmpnego = (Negocios) dao.findByWhereStatementoneobj(Negocios.class, "direccion = '" + txtdireccion.getText().toUpperCase() + "'");
                if (tmpnego == null) {
                    tmpnego = (Negocios) dao.findByWhereStatementoneobj(Negocios.class, "nombreempresa = '" + txtnempresa.getText().toUpperCase() + "'");
                    if (tmpnego == null) {
                        tmpnego = (Negocios) dao.findByWhereStatementoneobj(Negocios.class, "nis = '" + txtnis.getText().toUpperCase() + "'");
                        if (tmpnego == null) {
                            tmpnego = (Negocios) dao.findByWhereStatementoneobj(Negocios.class, "cuentacorriente = '" + txtctacorriente.getText().toUpperCase() + "'");
                            if (tmpnego == null) {
                                if (contribuyente == null) {
                                    contribuyente = (Contribuyentes) dao.findByWhereStatementOneJoinObj(Contribuyentes.class, " as b inner join b.usuarios as a where (a.nombres || ' ' || a.apellidos || ' - DUI:' || b.dui) = '" + cmbcontribuyente.getSelectedItem().toString() + "'");
                                }
                                tipo = (Tiposcomercio) dao.findByWhereStatementoneobj(Tiposcomercio.class, "actividadeconomica = '" + cmbactividad.getSelectedItem().toString() + "'");
                                activo = (Estados) dao.findByWhereStatementoneobj(Estados.class, "id = 1");
                                /*Llenando las Propiedades del Nuevo Negocio*/
                                negocio = new Negocios();
                                negocio.setContribuyentes(contribuyente);
                                negocio.setDireccion(txtdireccion.getText().toUpperCase());
                                negocio.setEstados(activo);
                                negocio.setFecha_registro(jdfecharegistro.getDate());
                                negocio.setGiros(giro);
                                negocio.setNis(txtnis.getText());
                                negocio.setNombreempresa(txtnempresa.getText().toUpperCase());
                                negocio.setTelefono(txttelefono.getText());
                                negocio.setTipos(tipo);
                                negocio.setCuentacorriente(txtctacorriente.getText().toUpperCase());
                                /*Comprobando si se ingresará el Valor Correspondiente a la Calificación del Negocio*/
                                if (!txtmontoneg.getText().isEmpty()) {
                                    montoimpuestonegocio = new Montosimpuestosnegocios();
                                    montoimpuestonegocio.setEstados(activo);
                                    montoimpuestonegocio.setFechainicio(codemd5.getmesanio(jdappmonto.getDate()));
                                    montoimpuestonegocio.setMonto(new BigDecimal(txtmontoneg.getText()).setScale(2, RoundingMode.HALF_EVEN));
                                    montoimpuestonegocio.setNegocios(negocio);
                                    montoimpuestonegocio.setUso("NO OBSOLETO");
                                    try {
                                        dao.save(negocio);
                                        dao.save(montoimpuestonegocio);
                                        JOptionPane.showMessageDialog(this, "Guardado Completo");
                                        LimpiarPantalla();
                                    } catch (Exception e) {
                                        JOptionPane.showMessageDialog(this, "Error en el Guardado de las Instancias");
                                        System.out.println(e.toString());
                                    }
                                } else {/*Guardando la Instancia del Negocio en caso no haya se aplique la calificación*/
                                    dao.save(negocio);
                                    JOptionPane.showMessageDialog(this, "Guardado Completo");
                                    LimpiarPantalla();
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "La Cuenta Corriente Debe Ser Unica. El Valor Ingresado ya ha sido asignado a un Negocio");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "El NIS Debe Ser Unico. El Valor Ingresado ya ha sido asignado a un Negocio");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El Nombre Ingresado Ya ha sido Asignado a Otro Negocio" + "\n Por Favor Verificar Antes de Guardar");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "La Direccion Ingresada ya ha sido Asignada a Otro Negocio" + "\n Por Favor Verificar Antes de Guardar");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingresar Todos los Datos Obligatorios Antes de Proceder a Guardar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error durante el Seteo de las propiedades");
            System.out.println(e.toString());
        }
    }

    /*Metodo utilizado para limpiar la información cargada en pantalla*/
    public void LimpiarPantalla() {
        componentes.limpiarmodelo(modelocontribuyente);
        modelocontribuyente.addElement("-");
        componentes.limpiarmodelo(modeloactividad);
        modeloactividad.addElement("-");
        txtnempresa.setText("");
        txttelefono.setText("");
        txtdireccion.setText("");
        txtnis.setText("");
        txtmontoneg.setText("");
        txtctacorriente.setText("");
        cmbgiro.setSelectedIndex(0);
        jdfecharegistro.setDate(new Date());
        jdappmonto.setDate(new Date());
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cmbcontribuyente = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbgiro = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbactividad = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtnis = new componentesheredados.NumberJTextField();
        jPanel3 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtnombres1 = new componentesheredados.LettersJTextField();
        jLabel22 = new javax.swing.JLabel();
        txtdui1 = new componentesheredados.DUITextField();
        jLabel23 = new javax.swing.JLabel();
        txtnit1 = new componentesheredados.NitJTextField();
        btnbuscar1 = new javax.swing.JButton();
        jbtnnombres1 = new javax.swing.JRadioButton();
        jbtndui1 = new javax.swing.JRadioButton();
        jbtnnit1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnempresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdfecharegistro = new com.toedter.calendar.JDateChooser();
        txttelefono = new componentesheredados.PhoneJTextField();
        jLabel12 = new javax.swing.JLabel();
        txtctacorriente = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtmontoneg = new componentesheredados.DecimalJTextField();
        jLabel10 = new javax.swing.JLabel();
        jdappmonto = new com.toedter.calendar.JDateChooser();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbcontribuyente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcontribuyenteActionPerformed(evt);
            }
        });

        jLabel8.setText("* Contribuyente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbcontribuyente, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbcontribuyente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 500, -1));

        jLabel3.setText("* Giro:");

        cmbgiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgiroActionPerformed(evt);
            }
        });

        jLabel4.setText("* Actividad:");

        cmbactividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbactividadActionPerformed(evt);
            }
        });

        jLabel11.setText(" NIS:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbactividad, 0, 146, Short.MAX_VALUE)
                    .addComponent(cmbgiro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbgiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbactividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 288, -1, 120));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnsalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 500, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Criterios de Busqueda");

        jLabel21.setText("Nombres:");

        jLabel22.setText("DUI:");

        try {
            txtdui1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel23.setText("NIT:");

        try {
            txtnit1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnbuscar1.setText("Buscar");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jbtnnombres1);
        jbtnnombres1.setText("Nombres y Apellidos");
        jbtnnombres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnombres1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jbtndui1);
        jbtndui1.setText("DUI");
        jbtndui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndui1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jbtnnit1);
        jbtnnit1.setText("NIT");
        jbtnnit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtnombres1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(42, 42, 42)
                        .addComponent(txtdui1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(txtnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jbtnnombres1)
                                .addGap(41, 41, 41)
                                .addComponent(jbtndui1)
                                .addGap(54, 54, 54)
                                .addComponent(jbtnnit1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(btnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar1)
                    .addComponent(jbtnnombres1)
                    .addComponent(jbtndui1)
                    .addComponent(jbtnnit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtnombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtdui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtnit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jLabel2.setText("* Nombre Empresa:");

        jLabel7.setText("* Dirección:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnempresa, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(txtdireccion)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 202, 500, -1));

        jLabel5.setText("Telefono:");

        jLabel6.setText("Fecha Registro:");

        try {
            txttelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("* Cta. Corriente:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtctacorriente)
                    .addComponent(jdfecharegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jdfecharegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtctacorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 288, -1, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Calificación del Negocio");

        jLabel9.setText("Monto:");

        jLabel10.setText("Fecha de Aplicación:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtmontoneg, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jdappmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdappmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtmontoneg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void cmbgiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgiroActionPerformed
        // TODO add your handling code here:
        if (cmbgiro.getSelectedItem() != null) {
            if (!cmbgiro.getSelectedItem().toString().equals("-")) {
                componentes.limpiarmodelo(modeloactividad);
                LlenarComboActividad();
                cmbgiro.setToolTipText(cmbgiro.getSelectedItem().toString());
            } else {
                componentes.limpiarmodelo(modeloactividad);
                modeloactividad.addElement("-");
                cmbgiro.setToolTipText(cmbgiro.getSelectedItem().toString());
            }

        }
    }//GEN-LAST:event_cmbgiroActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        GuardarDatosNegocio();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        // TODO add your handling code here:
        LimpiarPantalla();
        if (jbtnnombres1.isSelected()) {
            BuscarContribuyenteNombres();
        } else if (jbtndui1.isSelected()) {
            BuscarContribuyentesDui();
        } else if (jbtnnit1.isSelected()) {
            BuscarContribuyenteNit();
        } else {
            JOptionPane.showMessageDialog(this, "Elija un criterio de Busqueda e Ingrese el valor a buscar");
        }
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void jbtnnombres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnombres1ActionPerformed
        // TODO add your handling code here:
        txtnombres1.setEnabled(true);
        txtdui1.setEnabled(false);
        txtnit1.setEnabled(false);
        txtdui1.setText("");
        txtnit1.setText("");
        LimpiarPantalla();
    }//GEN-LAST:event_jbtnnombres1ActionPerformed

    private void jbtndui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndui1ActionPerformed
        // TODO add your handling code here:
        txtdui1.setEnabled(true);
        txtnit1.setEnabled(false);
        txtnombres1.setEnabled(false);
        txtnit1.setText("");
        txtnombres1.setText("");
        LimpiarPantalla();
    }//GEN-LAST:event_jbtndui1ActionPerformed

    private void jbtnnit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnit1ActionPerformed
        // TODO add your handling code here:
        txtnit1.setEnabled(true);
        txtnombres1.setEnabled(false);
        txtdui1.setEnabled(false);
        txtnombres1.setText("");
        txtdui1.setText("");
        LimpiarPantalla();
    }//GEN-LAST:event_jbtnnit1ActionPerformed

    private void cmbcontribuyenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcontribuyenteActionPerformed
        // TODO add your handling code here:
        if (cmbcontribuyente.getSelectedItem() != null) {
            if (!cmbcontribuyente.getSelectedItem().toString().equals("-")) {
                if (jbtnnombres1.isSelected()) {
                    contribuyente = (Contribuyentes) dao.findByWhereStatementOneJoinObj(Contribuyentes.class, " as b inner join b.usuarios as a where (a.nombres || ' ' || a.apellidos || ' - DUI:' || b.dui) = '" + cmbcontribuyente.getSelectedItem().toString() + "'");
                }
            }
            cmbcontribuyente.setToolTipText(cmbcontribuyente.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbcontribuyenteActionPerformed

    private void cmbactividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbactividadActionPerformed
        // TODO add your handling code here:
        if (cmbactividad.getSelectedItem() != null) {
            cmbactividad.setToolTipText(cmbactividad.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbactividadActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbactividad;
    private javax.swing.JComboBox cmbcontribuyente;
    private javax.swing.JComboBox cmbgiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jbtndui1;
    private javax.swing.JRadioButton jbtnnit1;
    private javax.swing.JRadioButton jbtnnombres1;
    private com.toedter.calendar.JDateChooser jdappmonto;
    private com.toedter.calendar.JDateChooser jdfecharegistro;
    private javax.swing.JTextField txtctacorriente;
    private javax.swing.JTextField txtdireccion;
    private componentesheredados.DUITextField txtdui1;
    private componentesheredados.DecimalJTextField txtmontoneg;
    private javax.swing.JTextField txtnempresa;
    private componentesheredados.NumberJTextField txtnis;
    private componentesheredados.NitJTextField txtnit1;
    private componentesheredados.LettersJTextField txtnombres1;
    private componentesheredados.PhoneJTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
