/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package peralcaldia.MantenimientosIngreso;

import java.util.Iterator;
import java.util.List;
import peralcaldia.model.Estados;
import peralcaldia.model.Roles;
import controller.AbstractDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import peralcaldia.model.Usuarios;
import util.GCMPNativos;
import util.codemd5;

/**
 *
 * @author alex
 */
/*Pantalla destinada a la creacion de usuarios del sistema (Administradores, Cuentas Corientes, Catastro, Tesoreria)*/
public class addusuario extends javax.swing.JInternalFrame {

    AbstractDAO dao = new AbstractDAO();
    GCMPNativos componentes = new GCMPNativos();
    DefaultComboBoxModel rolmodel = new DefaultComboBoxModel();
    DefaultComboBoxModel estmodel = new DefaultComboBoxModel();    

    /**
     * Creates new form addusuario
     */
    public addusuario() {
        initComponents();
        cmbestado.setModel(estmodel);
        cmbrol.setModel(rolmodel);
        fillComboBoxrol();
        fillComboBoxestado();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 4);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*Metodo utilizado para la carga de los diferentes tipos roles que pueden ser ocupados por los
     * usuarios.*/
    private void fillComboBoxrol() {
        List lista = null;
        try {
            lista = dao.findByWhereStatement("Select rol from Roles where rol <> 'CONTRIBUYENTE' and rol <> 'USUARIO' ");
            componentes.llenarmodelo(rolmodel, lista);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /*Metodo utilizado para cargar los diferentes estados que pueden ser ocupados por los Usuarios.*/
    private void fillComboBoxestado() {
        List lista = null;        
        try {
            lista = dao.findByWhereStatement("Select estado from Estados where estado = 'ACTIVO' or estado='INACTIVO' ");
            componentes.llenarmodelo(estmodel, lista);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /*Metodo encargado de la verificacion, inicializacion y seteo de las propiedades de los nuevos usuarios, asi como 
     * el guardado de la misma cuando esta cumple todos los requisitos*/
    public void guardarusuario() {
        //Declarando Variables.
        String key;
        Usuarios user = new Usuarios();
        Roles rl = new Roles();
        Estados st = new Estados();

        //Encriptando password.
        key = codemd5.getmd5(txtpassword.getText());        
        //Realizando Comprobacion de Campos Mandatorios.        
        if (!txtapellidos.getText().isEmpty() && !txtdireccion.getText().isEmpty() && !txtemail.getText().isEmpty() && !txtmovil.getText().isEmpty() && !txtnombres.getText().isEmpty() && !txtpassword.getText().isEmpty() && !txttelefono.getText().isEmpty() && !txtusername.getText().isEmpty() && !cmbestado.getSelectedItem().toString().equals("-") && !cmbrol.getSelectedItem().toString().equals("-")) {
            //Seteando las variables a las valores introducidos por el usuario.
            //Usuario
            rl = (Roles) dao.findByWhereStatementoneobj(Roles.class, "rol='" + cmbrol.getSelectedItem().toString() + "'");
            st = (Estados) dao.findByWhereStatementoneobj(Estados.class, "estado='" + cmbestado.getSelectedItem().toString() + "'");
            user.setApellidos(txtapellidos.getText().toUpperCase());
            user.setDireccion(txtdireccion.getText().toUpperCase());
            user.setEstados(st);
            user.setNombres(txtnombres.getText().toUpperCase());
            user.setPassword(key);
            user.setRoles(rl);
            user.setTelefonocelular(txtmovil.getText());
            user.setTelefonofijo(txttelefono.getText());
            //Comprobando que el Alias y el Email no hayan sido regsitrados.
            try {
                Usuarios cmpalias = new Usuarios();
                cmpalias = (Usuarios) dao.findByWhereStatementoneobj(Usuarios.class, "alias='" + txtusername.getText() + "'");
                if (cmpalias == null) {
                    cmpalias = (Usuarios) dao.findByWhereStatementoneobj(Usuarios.class, "email='" + txtemail.getText() + "'");
                    if (cmpalias == null) {
                        user.setAlias(txtusername.getText());
                        user.setEmail(txtemail.getText());
                        dao.save(user);
                        JOptionPane.showMessageDialog(this, "Guardado Completado");
                        limpiarcampos();
                    } else {
                        JOptionPane.showMessageDialog(this, "Correo registrado, Ingresar uno diferente");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario ya existe, por favor ingresar un usuario diferente");
                }

            } catch (Exception e) {
                System.out.println(e.toString());
                JOptionPane.showMessageDialog(this, "Hubo un error en el procesamiento de la información. Intentelo mas tarde");
            }            
        }else {
            JOptionPane.showMessageDialog(this, "Favor de Ingresar todos los campos necesarios para la creación del usuario");
        }
    }
    
    /*Metodo para limpiar la informacion Cargada en Pantalla*/
    public void limpiarcampos(){
        txtapellidos.setText("");
        txtdireccion.setText("");
        txtemail.setText("");
        txtmovil.setText("");
        txtnombres.setText("");
        txtpassword.setText("");
        txttelefono.setText("");
        txtusername.setText("");
        cmbestado.setSelectedIndex(0);
        cmbrol.setSelectedIndex(0);
        
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbrol = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbestado = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();
        txtnombres = new componentesheredados.LettersJTextField();
        txtapellidos = new componentesheredados.LettersJTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtemail = new componentesheredados.MailTextField();
        txttelefono = new componentesheredados.PhoneJTextField();
        txtmovil = new componentesheredados.PhoneJTextField();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("ROL:");

        cmbrol.setName(""); // NOI18N

        jLabel2.setText("ESTADO:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Username:");

        jLabel6.setText("Password:");

        jLabel7.setText("Email:");

        jLabel8.setText("Telefono:");

        jLabel9.setText("Celular:");

        jLabel10.setText("Dirección:");

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jbsalir.setLabel("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        try {
            txttelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtmovil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbrol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpassword)
                            .addComponent(txtdireccion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(jbsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addComponent(txtusername)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnombres, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(txtapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmovil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cmbrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtmovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(jbsalir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        guardarusuario();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbsalirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox cmbestado;
    private javax.swing.JComboBox cmbrol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbsalir;
    private componentesheredados.LettersJTextField txtapellidos;
    private javax.swing.JTextField txtdireccion;
    private componentesheredados.MailTextField txtemail;
    private componentesheredados.PhoneJTextField txtmovil;
    private componentesheredados.LettersJTextField txtnombres;
    private javax.swing.JPasswordField txtpassword;
    private componentesheredados.PhoneJTextField txttelefono;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
