/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package peralcaldia;

import javax.swing.JOptionPane;
import util.cobrosiniciales;

/**
 *
 * @author alex
 */
public class gencobrosmensuales extends javax.swing.JInternalFrame {

    /**
     * Creates new form gencobrosmensuales
     */
    public gencobrosmensuales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncobrosmensuales = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        btncobrosmensuales.setText("Generar Cobros Mensuales");
        btncobrosmensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrosmensualesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btncobrosmensuales, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btncobrosmensuales)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncobrosmensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrosmensualesActionPerformed
        // TODO add your handling code here:
        cobrosiniciales cobro = new cobrosiniciales();
        int contador = 0;
        String salida = "";
        try {
            if (cobro.generarcobrosmensualesinmuebles()) {
                contador = contador + 1;
            } else {
                salida = "No se generaron los cobros para los inmuebles";
            }

            if (cobro.generarcobrosmensualesnegocios()) {
                contador = contador + 1;
            } else if (contador == 1) {
                salida = "No se generaron los cobros para los negocios";
            } else {
                salida = salida + ("Tampoco para los negocios");
            }

            if (contador == 2) {
                JOptionPane.showMessageDialog(this, "PROCESO TERMINADO ");
            } else {
                JOptionPane.showMessageDialog(this, "PROCESO TERMINADO. " + salida);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Hubo un error en el proceso contacte al administrador de su red");
        }
        
    }//GEN-LAST:event_btncobrosmensualesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncobrosmensuales;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
